name        : gnome-settings-daemon
version     : 3.18.1
release     : 17
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-settings-daemon/3.18/gnome-settings-daemon-3.18.1.tar.xz : fa621a17f1d132fe60461020b0dad20a9fab6b0e3e651628aaa53a8f6a6df2c0
license     :
    - GPL-2.0
summary     : Daemon handling the GNOME session settings
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(libnotify)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(packagekit-glib2)
    - pkgconfig(xtst)
    - pkgconfig(ibus-1.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(upower-glib)
    - pkgconfig(xrandr)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(colord)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(xorg-wacom)
    - pkgconfig(libwacom)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(nss)
    - pkgconfig(NetworkManager)
    - cups-devel
description : |
    This package contains the daemon which is responsible for setting the various parameters of a GNOME session and the applications that run under it.
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-tap-to-click-by-default.patch
    %patch -p1 < $pkgfiles/0001-xsettings-Use-traditional-titlebar-layout-on-CSD-usi.patch
    %patch -p1 < $pkgfiles/font_fixes.patch
    
    %configure --disable-static \
               --disable-man \
               --enable-packagekit \
               --enable-network-manager \
               --enable-systemd
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
