name       : gnome-settings-daemon
version    : 3.24.1
release    : 26
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-settings-daemon/3.24/gnome-settings-daemon-3.24.1.tar.xz : 1b14ddc63e4cee616b73d048112878f6f4ac606f877778db882d270db904750b
license    :
    - GPL-2.0
component  : desktop.gnome.core
summary    : Daemon handling the GNOME session settings
description: |
    This package contains the daemon which is responsible for setting the various parameters of a GNOME session and the applications that run under it.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(colord)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(ibus-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgeoclue-2.0)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwacom)
    - pkgconfig(NetworkManager)
    - pkgconfig(nss)
    - pkgconfig(upower-glib)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xorg-wacom)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - cups-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-tap-to-click-by-default.patch
    %patch -p1 < $pkgfiles/0001-xsettings-Use-traditional-titlebar-layout-on-CSD-usi.patch
    %patch -p1 < $pkgfiles/font_fixes.patch

    %configure --disable-static \
               --disable-man \
               --enable-network-manager \
               --enable-systemd
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
