name       : gnome-settings-daemon
version    : 3.36.0
release    : 46
source     :
    - https://download.gnome.org/sources/gnome-settings-daemon/3.36/gnome-settings-daemon-3.36.0.tar.xz : fa2ff032ec6c59e4c4ca66c61a29f4ba4b9820496625fc343bfa12291cfaad49
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : Daemon handling the GNOME session settings
description: |
    This package contains the daemon which is responsible for setting the various parameters of a GNOME session and the applications that run under it.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(colord)
    - pkgconfig(gcr-base-3)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gweather-3.0)
    - pkgconfig(ibus-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgeoclue-2.0)
    - pkgconfig(libnm)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwacom)
    - pkgconfig(mm-glib)
    - pkgconfig(nss)
    - pkgconfig(upower-glib)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xorg-wacom)
    - pkgconfig(xrandr)
    - cups-devel
rundeps    :
    - bluez
    - gvfs
    - udisks
    - upower
setup      : |
    %patch -p1 < $pkgfiles/0001-Apply-Solus-defaults.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
