name       : gnome-settings-daemon
version    : 3.32.0
release    : 39
source     :
    - https://download.gnome.org/sources/gnome-settings-daemon/3.32/gnome-settings-daemon-3.32.0.tar.xz : c3b8035aced4971ac49d3f3a5faa301a0825607e73248666a5f8078793d58397
license    : GPL-2.0-only
component  : desktop.gnome.core
summary    : Daemon handling the GNOME session settings
description: |
    This package contains the daemon which is responsible for setting the various parameters of a GNOME session and the applications that run under it.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(colord)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(ibus-1.0)
    - pkgconfig(lcms2)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgeoclue-2.0)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libwacom)
    - pkgconfig(NetworkManager)
    - pkgconfig(nss)
    - pkgconfig(upower-glib)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(xorg-wacom)
    - pkgconfig(xrandr)
    - cups-devel
rundeps    :
    - bluez
    - gvfs
    - udisks
    - upower
setup      : |
    %patch -p1 < $pkgfiles/0001-Apply-Solus-defaults.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
