name        : gnome-settings-daemon
version     : 3.16.2
release     : 12
source      :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-settings-daemon/3.16/gnome-settings-daemon-3.16.2.tar.xz : d8d536584ebb8fb1403050eb65e7ee3328eba14b123542369ff1917e727fa69a
homepage    : http://www.gnome.org
license     :
    - GPLv2+
summary     : Daemon handling the GNOME session settings
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(libnotify)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(packagekit-glib2)
    - pkgconfig(xtst)
    - pkgconfig(ibus-1.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(upower-glib)
    - pkgconfig(xrandr)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(colord)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(xorg-wacom)
    - pkgconfig(libwacom)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
    - pkgconfig(nss)
    - pkgconfig(NetworkManager)
    - cups-devel
description : |
    This package contains the daemon which is responsible for setting the various parameters of a GNOME session and the applications that run under it.
setup      : |
    %configure --disable-static \
               --disable-man \
               --enable-packagekit \
               --enable-network-manager \
               --enable-systemd
build      : |
    %make
install    : |
    %make_install
